#ifndef CORE_MQTT_AGENT_MANAGER_EVENTS_H
#define CORE_MQTT_AGENT_MANAGER_EVENTS_H

#include "esp_event.h"

ESP_EVENT_DECLARE_BASE( CORE_MQTT_AGENT_EVENT );

enum
{
    CORE_MQTT_AGENT_CONNECTED_EVENT,
    CORE_MQTT_AGENT_DISCONNECTED_EVENT,
    CORE_MQTT_AGENT_OTA_STARTED_EVENT,
    CORE_MQTT_AGENT_OTA_STOPPED_EVENT
};

#endif /* CORE_MQTT_AGENT_MANAGER_EVENTS_H */
